printCard/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("printAdhar.urls")),
    path('u/', include("userApp.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userApp/urls.py
from django.urls import path, include
from .views import register_request, login_request, logout_request

app_name = "userApp"   


urlpatterns = [
    # path("", homepage, name="homepage"),
    path("register/", register_request, name="register"),
    path("login/", login_request, name="login"),
    path("logout/", logout_request, name= "logout"),
]

printAdhar/models.py
from django.db import models



class AdharCardDetail(models.Model):

    # Gender
    MALE = 'MALE'
    FEMALE = 'FEMALE'

    GENDER_CHOICE ={
            (MALE, 'MALE'),
            (FEMALE , 'FEMALE'),
        }

    # State
    MP = "Madhya Pradesh"
    CG = "Chhattisgarh"

    STATE_CHOICE={
        (MP, "Madhya Pradesh"),
        (CG, "Chhattisgarh"),
    }

    # Relation type
    SON_OF = "S/O"
    DAUGHTER_OF = "D/O"
    WIFE_OF = "W/O"

    RELATION_CHOICE = {
        (SON_OF, "S/O"),
        (DAUGHTER_OF, "D/O"),
        (WIFE_OF, "W/O"),
    }

    uid = models.BigIntegerField(verbose_name="Adhar Aumber")
    full_name = models.CharField(max_length=100, verbose_name='Full Name (English)')
    relation = models.CharField(max_length=4, choices=RELATION_CHOICE, default=SON_OF, verbose_name="Relation")
    relation_name = models.CharField(max_length=100, verbose_name='Father/Husband (English)')
    date_of_birth = models.DateField(null=True, verbose_name='DOB')
    gender = models.CharField(choices=GENDER_CHOICE, max_length=8, default=MALE, verbose_name='Gender')
    image = models.ImageField(upload_to = "profile_image", verbose_name="Image")
    address = models.CharField(max_length=150, verbose_name='Address (English)', )
    city = models.CharField(max_length=20, verbose_name="City")
    state = models.CharField(choices=STATE_CHOICE, max_length=20, verbose_name="State", default=MP)

    full_name_hi = models.CharField(max_length=100, verbose_name='Full Name (Hindi)')
    relation_hi = models.CharField(max_length=20, verbose_name="Relation (hindi)")
    gender_hi = models.CharField(max_length=20, verbose_name='Gender (Hindi)')
    relation_name_hi = models.CharField(max_length=100, verbose_name='Father/Husband (Hindi)')
    address_hi = models.CharField(max_length=150, verbose_name='Address (Hindi)', )
    city_hi = models.CharField(max_length=20, verbose_name="City (Hindi)")
    state_hi = models.CharField(max_length=50, verbose_name="State (Hindi)")

    pin_code = models.CharField(max_length=6, default="482000", verbose_name= "PIN CODE")

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

printAdhar/forms.py
from django import forms
from .models import AdharCardDetail
from django.forms.fields import DateField
from django.forms import widgets



class AdharDetailFirstForm(forms.ModelForm):
    
    date_of_birth = DateField(widget=widgets.DateInput(attrs={'type': 'date'}))
    
    class Meta:
        model = AdharCardDetail
        exclude = ('full_name_hi', 'relation_hi', 'gender_hi', 'relation_name_hi', 'address_hi', 'city_hi', 'state_hi',)



class AdharDetailForm(forms.ModelForm):
    
    class Meta:
        model = AdharCardDetail
        fields = '__all__'

printAdhar/views.py
from functools import reduce
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import AdharCardDetail
from .forms import AdharDetailForm, AdharDetailFirstForm
from googletrans import Translator
from datetime import datetime
from dateutil.relativedelta import relativedelta



def index(request):
    
    data = '''Rajendra Kumar, chitarwai kala, khutar, singrauli, madhya pradesh
    contact: 9009112115
    '''
    return render(request, 'dasboard.html', {'data': translate_to_hindi(data)})
    

def translate_to_hindi(text):
    try:
        translator = Translator()
        return translator.translate(text, dest='hi').text
    except AttributeError:
        return None


@login_required
def adhar_form(request):

    if request.method == "POST":
        form = AdharDetailFirstForm(request.POST, request.FILES)
        
        name = request.POST.get('full_name')
        form.instance.full_name_hi = translate_to_hindi(name)
        # print(request.POST.get('relation'))

        if request.POST.get('relation') == "S/O":
            form.instance.relation_hi = translate_to_hindi("atmaj")
        elif form.instance.relation == "W/O":
            form.instance.relation_hi = translate_to_hindi("ardhangani")
        else:
            form.instance.relation_hi = translate_to_hindi("aatmja")


        if request.POST.get('gender') == "MALE":
            form.instance.gender_hi = translate_to_hindi("purush")
        else :
            form.instance.gender_hi = translate_to_hindi("mahila")

        form.instance.relation_name_hi = translate_to_hindi(request.POST.get('relation_name'))
        form.instance.address_hi = translate_to_hindi(request.POST.get('address'))
        # print(form.instance.address_hi)
        form.instance.city_hi = translate_to_hindi(request.POST.get('city'))
        form.instance.state_hi = translate_to_hindi(request.POST.get('state'))

        # return render(request, 'uid/adhar_form.html', {'form': form})

        if form.is_valid():
            print("Form is vailidated and saved...")
            form.save()
            return redirect('adhar_list')
        else:
            return render(request, 'uid/adhar_form.html', {'form': form})
    else:
        form = AdharDetailFirstForm()
        return render(request, 'uid/adhar_form.html', {'form': form})


@login_required
def adhar_list(request):
    
    adhar_list = AdharCardDetail.objects.all() 
    return render(request, 'uid/adhar_list.html', {'data': adhar_list})


@login_required
def print_adhar(request, id):
    
    try:
        data = AdharCardDetail.objects.get(id=id)

        adhar_number = ""
        uid=str(data.uid)

        # this loop return the uid no in format which is in int uid no 
        for i in range(0,14):
            if i < 4:
                adhar_number += uid[i]
            elif i == 4 or i == 9:
                adhar_number += " "
            elif i < 9:
                adhar_number += uid[i-1]
            elif i < 15:
                adhar_number += uid[i-2]
            else:
                adhar_number.append("")

        download_date = datetime.now()
        issue_date = datetime.now() - relativedelta(years=3, days=8)
        string = str(data.uid) + " " + data.full_name + " " + data.relation + " " + data.relation_name + " " + str(data.date_of_birth) + " " + data.gender + " " + data.address + " " + data.city + " " + data.state + " " +data.full_name_hi + " " + data.relation_hi + " " + data.relation_name_hi + " " + data.gender_hi + " " + data.address_hi + " " + data.city_hi + " " + data.state_hi + " " + str(data.pin_code) + " " + str(data.image)
        string += " " + str(download_date) + str(issue_date)
        string += ", This is fack Adhar Download From Fack site 'Raj Infotech Printing Service' for any frod this site will not responsible"
        qr_text = reduce(lambda x, y: str(x)+str(y), map(ord,string))
        
        context = {
            'data': data, 
            'uid': adhar_number, 
            'qr_text': qr_text,
            'download_date': download_date,
            'issue_date': issue_date
        }

        return render(request, 'uid/print_adhar.html', context)
        
    except AdharCardDetail.DoesNotExist:
        return render(request, 'uid/adhar_view.html', {'data': None})


@login_required
def update_adhar(request, id):
    
    instance = get_object_or_404(AdharCardDetail, id=id)
    form = AdharDetailForm(request.POST or None, request.FILES or None, instance=instance)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("adhar_list")
        else:
            return render(request, "uid/adhar_updtae_form.html", {"form": form})
    return render(request, "uid/adhar_updtae_form.html", {"form": form})


@login_required
def delete_adhar(request, id):
    
    try:
        data = AdharCardDetail.objects.get(id=id)
        data.delete()
        return redirect('adhar_list')
    except AdharCardDetail.DoesNotExist:
        print("Unable to delete")
        return redirect('adhar_list')

printAdhar/templates/dasboard.html
{% extends "layout.html" %}
{% block content %}

    {{data}}

{% endblock %}

printAdhar/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Raj Infotech Printing</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>

    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                {% comment %} <div class="sidebar-heading border-bottom bg-light">Start Bootstrap</div> {% endcomment %}
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3 {% if request.resolver_match.url_name == 'index'%}active{% endif %}" href="{% url 'index' %}">Dashboard</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3 {% if request.resolver_match.url_name == 'adhar_form'%}active{% endif %}" href="{% url 'adhar_form' %}">Add Adhar</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3 {% if request.resolver_match.url_name == 'adhar_list'%}active{% endif %}" href="{% url 'adhar_list' %}">Adhar List</a>
                    
                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        {% comment %} sidebar {% endcomment %}
                        <button class="btn" id="sidebarToggle"><i class="fas fa-bars"></i></button>
                        <h3 class="text-primary m">Raj Infotech Printing Service</h3>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        {% comment %} Top menu bar option {% endcomment %}
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                <li class="nav-item active"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
                                {% if user.is_authenticated %}
                                    <li class="nav-item"><a class="nav-link" href="{% url 'adhar_list' %}">Print Adhar</a></li>
                                {% else %}
                                    <li class="nav-item"><a class="nav-link" href="{% url 'userApp:register' %}">Register</a></li>
                                {% endif %}
                                
                                {% if user.is_authenticated %}
                                    <li class="nav-item dropdown">
                                        {% comment %} Top nav menu Profile {% endcomment %}
                                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="far fa-user-circle"></i></a>
                                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="#">Profile</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">Logout</a>
                                        </div>
                                    </li>
                                {% else %}
                                    <li class="nav-item"><a class="nav-link" href="{% url 'userApp:login' %}">Login</a></li>
                                {% endif %}

                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                    <div class="news mx-5">
                        <marquee class="news-content" scrollamount="12" onMouseOver="this.stop()" onMouseOut="this.start()">
                            <div class="alert alert-danger" role="alert">यह पूरी तरह से फेक और मैनुअल कार्ड बनाने का एक तारीका है, जिसका जिम्मेदार न तो एडमिन है और ना ही सरकार | किसी भी धोखाधड़ी की जिम्मेदारी कार्ड बनाने वाले की होगी ...</div>
                        </marquee>
                    </div>
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>